### ISSUE TITLE
Huge Option

### ISSUE THREAD

**Issue by Segelzwerg** [tkrajina/gpxpy#110]
Hi folks,

I get an exception: 

> Excessive depth in document: 256 use XML_PARSE_HUGE option, line 769, column 5 (<string>, line 769)
At first I thought there was an issue with special chars in the file name, but even with clean file names some files raises that error.

Do you need anything else?

Cheers, Marcel

**Comment by tkrajina** [comment]
Two ideas. First of all you are using lxml. Try uninstalling it and gpxpy will fallback to the default parser and it should work (but it will be slow).

The lxml parsing at https://github.com/tkrajina/gpxpy/blob/master/gpxpy/parser.py#L46 should include the fix described here https://stackoverflow.com/questions/11850345/using-python-lxml-etree-for-huge-xml-files . 

Note, if somebody plan to fix this in a pull request, do it from `dev`, since the code there changed from the current `master`.
