### ISSUE TITLE
ParseError while posting file with request

### ISSUE THREAD

**Issue by kiranlm** [tkrajina/gpxpy#204]
I have tried to read file from request instead of physical path
```python
gpxFile = request.files['gpx'].read()
gpx = gpxpy.parse(gpxFile)

```
This one give me some error like:
```bash
File "C:\Users\kiran\anaconda3\envs\runcoach\lib\xml\etree\ElementTree.py", line 1315, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1
```
Below one is working fine when I tried reading from local file:
```python
gpx_file = open('data/tcs.gpx', 'r')
gpx = gpxpy.parse(gpx_file)
```
**How can I parse the file from request**

I'm posting as FormData like this:
![image](https://user-images.githubusercontent.com/5306693/84191847-bd9a5780-aab6-11ea-863b-eeb18b3a62ca.png)

**Comment by tkrajina** [comment]
`gpxpy.parse(gpxFile)` accepts a file-like object or a string. In this case it probably isn't a valid file-like object or it's not a string. Log the type and contents of `gpxFile` to see what's in there.

Anyway, I'm closing this since this isn't an "issue" (it's a question - stackoverflow is a better places for asking questions).
