### ISSUE TITLE
Splits calculation

### ISSUE THREAD

**Issue by bjorntheart** [tkrajina/gpxpy#70]
Is it possible to calculate kilometer(km) splits including data such as km, pace, (+-) elevation with this tool?

I also noticed that **point.speed** is **None**, but **point.exentions['gpxdata:speed]** is populated. What is the **extensions** attribute? I couldn't find any helpful resources online.

**Comment by tkrajina** [comment]
If your "splits" are already stored as tracks/segments of a GPX file, you can use `gpxinfo` for something similar. 

Your `point.exentions['gpxdata:speed]` is populated because your GPX (1.1) file probably have `<extensions><gpxdata:speed>...</gpxdata:speed></extenstions>` stored for every point.

See here: https://github.com/tkrajina/gpxpy/issues/69 for a better description on the missing `speed` attribute.

**Comment by bjorntheart** [comment]
I guess I can run the gpxinfo utility every time a gpx file is uploaded to my web app. I'll have to write a parser to strip out the labels(description for the data for each line) for each line to get the raw data for example: Moving time: 00:51:39 becomes 00:51:39

Is the raw information, without the labels, available through gpxpy parser or something?

**Comment by tkrajina** [comment]
If your webapp is in python, why don't you just copy-paste and change the code from https://github.com/tkrajina/gpxpy/blob/master/gpxinfo ? If you plan to execute gpxinfo -- you can change the code to make the output whatever you want.

In case you want a faster solution, you can use my Golang port of gpxpy: https://github.com/tkrajina/gpxgo

I can't help more than this.

**Comment by PabloCuenca** [comment]
Hi,  

Not sure if the question on kilometer splits was answered.... Sorry for asking again if I missed the answer but is there any way to calculate the split statistics? My gpx files have no "splits" stored as segments or tracks. 

Ideally what I´m looking for is statistics per distance step, being the distance step a parameter - typically 1km. 
Thanks
